name: First Workflow
on: workflow_dispatch
jobs:
  first-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Run multi-line Shell commands
        run:  |
            echo "First output"
            echo "Second output"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

      - name: Print goodbye
        run: echo "Done - bye"
  
